# Docker builder for Golang
FROM golang as builder
LABEL maintainer "Thomas Bouvier <contact@thomas-bouvier.io>"

WORKDIR /go/src/app
COPY ./src .
RUN go get -d -v . && \
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

# Golang application
FROM alpine
LABEL maintainer "Thomas Bouvier <contact@thomas-bouvier.io>"

RUN apk add --no-cache ca-certificates

WORKDIR /root
COPY --from=builder /go/src/app .

EXPOSE REPLACE_WITH_THE_API_PORT

CMD ["./app"]
